mentor = {'rolemodels': [{'group_id': 'group_1',
    'group_name': '백엔드 개발 전문가',
    'current_position': '백엔드 개발자',
    'experience_years': '10년',
    'main_domains': ['통신', '금융'],
    'advice_message': '백엔드 개발에 있어서는 기술 스택의 깊이를 쌓는 것이 중요합니다. 다양한 프로젝트 경험을 통해 실력을 키우세요.',
    'common_skill_set': ['Back-end Dev.',
     'Application Architect',
     'PMO',
     'Quality Eng.'],
    'common_career_path': ['개발자', 'PL', 'PM'],
    'common_project': ['통신사 CATMS 시스템 구축',
     '통신사 MOST 시스템 구축',
     '통신사 무선망 최적화 시스템'],
    'common_experience': ['PMO 자격증 취득', 'Quality Engineering 경험'],
    'common_cert': ['PMP', '기술사']},
   {'group_id': 'group_2',
    'group_name': '프로젝트 관리 및 개발 리더',
    'current_position': '프로젝트 매니저',
    'experience_years': '15년',
    'main_domains': ['공공', '의료'],
    'advice_message': '프로젝트 관리에서는 팀원과의 소통이 가장 중요합니다. 항상 열린 마음으로 의견을 수렴하세요.',
    'common_skill_set': ['PMO',
     'Application PM',
     'Sales',
     'System/Network Eng.'],
    'common_career_path': ['PM', 'PL', '개발자'],
    'common_project': ['제조 ERP 구축 프로젝트',
     '공공기관 방호탐지 관리 시스템',
     'IT서비스HV 차세대 영업 관리 시스템'],
    'common_experience': ['공공 프로젝트 수행 경험', '협업의 중요성 인식'],
    'common_cert': ['PMP', '기술사']}]}


group_1_data = mentor['rolemodels'][0]
print(group_1_data)