apiVersion: apps/v1
kind: Deployment
metadata:
  name: nav7-ai-deploy
  labels:
    app: nav7-ai
  namespace: sk-team-07   # 필요에 따라 네임스페이스 변경
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nav7-ai
  template:
    metadata:
      labels:
        app: nav7-ai
    spec:
      serviceAccountName: default
      containers:
        - name: nav7-ai
          image: amdp-registry.skala-ai.com/skala25a/sk-nav7-ai:1.0.0-29-08791b38e1ed
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: IMAGE_REGISTRY
              value: "amdp-registry.skala-ai.com/skala25a"
            - name: IMAGE_NAME
              value: "nav7-ai"
            - name: IMAGE_TAG
              value: "1.0.0"
            - name: PORT
              value: "8000"
