apiVersion: apps/v1
kind: Deployment
metadata:
  name: nav7-ai-deploy
  labels:
    app: nav7-ai
  namespace: sk-team-07   # 필요에 따라 네임스페이스 변경
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nav7-ai
  template:
    metadata:
      labels:
        app: nav7-ai
    spec:
      serviceAccountName: default
      containers:
        - name: nav7-ai


          image: amdp-registry.skala-ai.com/skala25a/sk-nav7-ai:1.0.0-2-9c7ac7ce55d0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: OPENAI_API_KEY
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: TAVILY_API_KEY
            - name: REDDIT_ID
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: REDDIT_ID
            - name: REDDIT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: REDDIT_SECRET
            - name: EMBEDDING_MODEL_NAME
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: EMBEDDING_MODEL_NAME
            - name: JSON_HISTORY_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: JSON_HISTORY_COLLECTION_NAME
            - name: LEC_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: LEC_COLLECTION_NAME
            - name: MODEL_NAME
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: MODEL_NAME
            - name: TEMPERATURE
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: TEMPERATURE
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: MONGO_URL
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: MONGO_DB
            - name: MONGO_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: MONGO_COLLECTION
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: POSTGRES_URL
            - name: REDDIT_AGENT
              valueFrom:
                secretKeyRef:
                  name: nav-ai-secret
                  key: REDDIT_AGENT
            - name: IMAGE_REGISTRY
              value: "amdp-registry.skala-ai.com/skala25a"
            - name: IMAGE_NAME
              value: "nav7-ai"
            - name: IMAGE_TAG
              value: "1.0.0"
            - name: PORT
              value: "8000"

